"""Add position to List and Card

Revision ID: 6bfb29647360
Revises: 
Create Date: 2026-04-11 22:37:37.258429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfb29647360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('boards_owner_id_fkey'), 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('cards', sa.Column('position', sa.Float(), nullable=False))
    op.drop_constraint(op.f('cards_list_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.add_column('lists', sa.Column('position', sa.Float(), nullable=False))
    op.drop_constraint(op.f('lists_board_id_fkey'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_board_id_fkey'), 'lists', 'boards', ['board_id'], ['id'])
    op.drop_column('lists', 'position')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_list_id_fkey'), 'cards', 'lists', ['list_id'], ['id'])
    op.drop_column('cards', 'position')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key(op.f('boards_owner_id_fkey'), 'boards', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
